# The main purpose of this file is to be able to reuse the configuration to run tests
spring:
  datasource:
    url: jdbc:postgresql://objectstore_test_postgres/object_store_test
    username: test
    password: test
  liquibase:
    # To run migration as another user
    url: jdbc:postgresql://objectstore_test_postgres/object_store_test
    user: test
    password: test
minio:
  port:  9000
  accessKey:  minio 
  secretKey:  minio123
