language: java

services:
  - docker

cache:
  directories:
  - $HOME/.m2

script: 
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check
  - if [ "$TRAVIS_BRANCH" == "dev" ]; then mvn org.owasp:dependency-check-maven:check; fi
 
jdk:
  - openjdk11
  - openjdk12
  - openjdk13
