language: java

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.m2

before_script:
  - psql -c "CREATE DATABASE objectstore_test_db;" -U postgres
  - psql -c "CREATE USER test WITH PASSWORD 'test';" -U postgres

script: 
  - mvn verify -Dspring.datasource.url=jdbc:postgresql://localhost/objectstore_test_db -D -Dspring.datasource.username=test -D-Dspring.datasource.password=test checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check
 
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
