# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- dev

pool:
  vmImage: ubuntu-latest

steps:

- powershell: |
     $nvdcachepath = $(get-childitem "$(Agent.WorkFolder)\_tasks\dependency-check-build-task*\*.*.*\dependency-check\data").FullName
     echo "##vso[task.setvariable variable=nvdcachepath;]$nvdcachepath"
  displayName: Get NVD Cache path

- task: Cache@2
  inputs:
    key: '"NVDDataCache"'
    path: $(nvdcachepath)
  displayName: NVD Data Cache

- task: dependency-check-build-task@6
  inputs:
    projectName: 'object-store-api'
    scanPath: '**/*.jar'
    format: 'HTML, JUNIT'
    failOnCVSS: '8'
    suppressionPath: 'owasp-suppression.xml'

- task: PublishTestResults@2
  displayName: 'Publish OWASP Dependency Check results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'dependency-check/*junit.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    testRunTitle: 'Dependency Check'
    buildConfiguration: '$(BuildConfiguration)'
