# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: dependency-check-build-task@6
  inputs:
    projectName: 'object-store-api'
    scanPath: '$(Pipeline.Workspace)'
    format: 'XML'
    failOnCVSS: '8'
    suppressionPath: 'owasp-suppression.xml'

- task: PublishTestResults@2
  displayName: 'Publish OWASP Dependency Check results'
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: 'dependency-check/*junit.xml'
    searchFolder: '$(Common.TestResultsDirectory)'
    testRunTitle: 'Dependency Check'
    buildConfiguration: '$(BuildConfiguration)'
