= API

== Additional Endpoints

=== resource-name-identifier
Get the identifier (UUID) based on the name, the type and the group.

GET `/resource-name-identifier?filter[type][EQ]=metadata&filter[name][EQ]=name1&filter[group][EQ]=aafc`

Available for types :

* metadata

== Administrative Endpoints

Unless explicitly mentioned administrative endpoints require `DINA_ADMIN` role.

=== Regenerate Thumbnails

Send a POST request to `derivative-generation` with a body like:
```
{
  "data": {
    "type": "derivative-generation",
    "attributes": {
      "metadataUuid": "uuid of the original object",
      "derivativeType": "THUMBNAIL_IMAGE",
      "derivedFromType": "LARGE_IMAGE"
    }
  }
}
```

That will instruct the api to generate a thumbnail from the large image derivative. This should be used in cases where the
original object can not be used to create the thumbnails (like raw image files). Otherwise, `derivedFromType` should simply be omitted to
use the original object as a source.

=== Index Refresh

Trigger a message to (re)index a resource.

POST `/index-refresh`

```json
{
  "data": {
    "type": "index-refresh",
    "id": "c9e66a08-8b59-4183-8346-e2298af32bfe",
    "attributes": {
      "docType": "metadata"
    }
  }
}
```
