= File/Derivative Upload and Download

== Upload a file

1. Send a POST request to the `/api/v1/file/{bucket}` endpoint.

Example request:

```sh
curl -i http://localhost:8081/api/v1/file/mybucket -F file=@./my-image.png;type=image/png
```

Example response:

```sh
{
	"fileIdentifier": "0050559c-beae-48d6-a2b0-91f5a666fad1",
	"metaFileEntryVersion": "1.0",
	"originalFilename": "example-png.png",
	"sha1Hex": "c0c1d898ed827d6db02a03df941225184277d9e5",
	"receivedMediaType": "image/png",
	"detectedMediaType": "image/png",
	"detectedFileExtension": ".png",
	"evaluatedMediaType": "image/png",
	"evaluatedFileExtension": ".png",
	"sizeInBytes": 976,
	"thumbnailIdentifier": "b9f6f58b-1b41-400f-b178-f91d11221b7c"
}

```

2. Send a POST request to the `/api/v1/metadata` endpoint to create a Metadata record for the stored
object, using the fileIdentifier from the upload response.

```sh
curl -X POST http://localhost:8081/api/v1/metadata \
-H "Content-Type: application/vnd.api+json" \
-H "Accept: application/vnd.api+json" \
--data-binary @- << EOF
{
  "data": {
    "type": "metadata",
    "attributes": {
      "bucket": "mybucket",
      "dcType": "Image",
      "fileExtension": ".png",
      "fileIdentifier": "0050559c-beae-48d6-a2b0-91f5a666fad1"
    }
  }
}
EOF
```

== Upload a Derivative

Uploading a Derivative is similar to uploading a regular file.

However, a derivative will be expected to derive from an existing file with an existing metadata for the original file.

*1. Upload the derivative file by sending a post request to: `/api/v1/file/{bucket}/derivative` with the file as multipart/form-data.*

> Example Request: POST /api/v1/file/{bucket}/derivative
```sh
curl --request POST \
  --url http://localhost:8081/api/v1/file/dev-group/derivative \
  --header 'Content-Type: multipart/form-data; boundary=---011000010111000001101001' \
  --form file=@/home/jon/object-store-api/src/test/resources/drawing.png
```

> Example response:
```json
{
  "id": 2,
  "fileIdentifier": "5c158d6e-09eb-4272-88b6-3349b638100d",
  "dcType": "IMAGE",
  "createdBy": "dev",
  "createdOn": null,
  "originalFilename": "drawing.png",
  "sha1Hex": "3a37e3546074b6a67afef2fc1b402bf9233a1eb7",
  "receivedMediaType": "image/png",
  "detectedMediaType": "image/png",
  "detectedFileExtension": ".png",
  "evaluatedMediaType": "image/png",
  "evaluatedFileExtension": ".png",
  "sizeInBytes": 6091,
  "thumbnailIdentifier": null,
  "bucket": "dev-group",
  "exif": {},
  "dateTimeDigitized": null,
  "isDerivative": true,
  "group": null
}
```

*2. Upload the derivative resource for that file at: `api/v1/derivative/`*

The fileIdentifier in the following example points to the returned file Identifier for step one. This identifies the uploaded derivative.

The acDerivedFrom object in the following example represents the original resource this derivative will derive from.

> Example Request: POST /api/v1/derivative/
```sh
curl --request POST \
  --url http://localhost:8081/api/v1/derivative/ \
  --header 'Content-Type: application/vnd.api+json' \
  --data '{
	"data": {
		"type": "derivative",
		"attributes": {
			"dcType": "SoUnD",
			"fileIdentifier": "5c158d6e-09eb-4272-88b6-3349b638100d"
		},
		"relationships": {
			"acDerivedFrom": {
				"data": {
					"id": "e39ba089-4757-433a-a787-2287b3defb46",
					"type": "metadata"
				}
			}
		}
	}
}'
```

== Uploading a thumbnail for a specific resource

You can upload a derivative to be a thumbnail for an Object.

After uploading a derivative file, when the derivative resource for that file is being uploaded 2 things will be required.

1. You must set `"derivativeType": "THUMBNAIL_IMAGE"` as shown in the following example.
2. You must provide a valid `acDerivedFrom object`.

> Example Request: POST /api/v1/derivative/
```sh
curl --request POST \
  --url http://localhost:8081/api/v1/derivative/ \
  --header 'Content-Type: application/vnd.api+json' \
  --data '{
	"data": {
		"type": "derivative",
		"attributes": {
			"fileIdentifier": "df85bc1b-7365-4621-ab00-2cdd48808252",
			"dcType": "Image",
			"derivativeType": "THUMBNAIL_IMAGE"
		},
		"relationships": {
			"acDerivedFrom": {
				"data": {
					"id": "c8b71e52-ccf1-4409-8d3d-deb23e0a9906",
					"type": "metadata"
				}
			}
		}
	}
}'
```

WARNING: this does not resize the image! If you want an image to be resized and used as a thumbnail, submit the image as a regular derivative with a provided `acDerivedFrom` and a thumbnail will be generated for this image and associated with the given `acDerivedFrom`.

== File Download

To download a stored object, send a GET request to the `/api/v1/file/{bucket}/{fileId}` endpoint.

Example request:

```sh
curl http:/localhost:8081/api/v1/file/mybucket/0050559c-beae-48d6-a2b0-91f5a666fad1 > my-downloaded-image.png
```

== Thumbnail File Download

To download a thumbnail, send a GET request to the `/api/v1/file/{bucket}/{fileId}/thumbnail` endpoint.

A thumbnail is automatically generated after an image file's metadata is uploaded.


== Derivative File Download

To download a stored derivative, send a GET request to the `/api/v1/file/{bucket}/derivative/{fileId}` endpoint.

> Example Request: GET /api/v1/file/{bucket}/derivative/{fileId}
```sh
curl --request GET \
  --url http://localhost:8081/api/v1/file/dev-group/derivative/cbb9484a-67f1-4112-accd-829bdfa0ad9e
```